openapi: 3.1.0
info:
  title: Light service
servers:
- url: http://localhost:8080/light
  description: API (light)
paths:
  /sensors/turn-on/{id}:
    put:
      tags:
      - light-controller
      summary: Включить свет
      operationId: turnOn
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema: {}
              examples:
                example400:
                  value:
                    status: 400
                    message: Bad request
                    detailMessage: Illegal parameter
        "404":
          description: Resource Not Found
          content:
            application/json:
              schema: {}
              examples:
                example404:
                  value:
                    status: 404
                    message: Not Found
                    detailMessage: NotFoundException
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema: {}
              examples:
                example500:
                  value:
                    status: 500
                    message: Internal Server Error
                    detailMessage: RuntimeException
  /sensors/turn-off/{id}:
    put:
      tags:
      - light-controller
      summary: Выключить свет
      operationId: turnOff
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema: {}
              examples:
                example400:
                  value:
                    status: 400
                    message: Bad request
                    detailMessage: Illegal parameter
        "404":
          description: Resource Not Found
          content:
            application/json:
              schema: {}
              examples:
                example404:
                  value:
                    status: 404
                    message: Not Found
                    detailMessage: NotFoundException
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema: {}
              examples:
                example500:
                  value:
                    status: 500
                    message: Internal Server Error
                    detailMessage: RuntimeException
components: {}
